remove navigation bar
contined in frameworks base
option to remove navbar and select full guesture mode

Enable developer settings by default [2/2].

Change-Id: Ia3ec00857f9c1615eaf8aba8d4db26150d8b7333

Add files via upload

add orchid logo

Add files via upload

add orchid logo

Lottie Animations

Update dimens.xml

introducing app warden

Update strings.xml

fix info added

added app warden

test

logo fix

Create liquid_logo.xml

typo

logo fix important

fix card bg

Add files via upload

Delete androidsystem.xml

Update googlebanner_animation.xml

Create googlebanner.json

fix

fix

add extra settings

Revert "add extra settings"

This reverts commit b1a0ee6a144bbd9e6ac5c76b0f1d013b49933368.

test

rebrand to orchidos

rebrand the strings to orchid os test

fix error: mismatched tag: line 3346

fAILED: out/target/common/obj/APPS/Settings_intermediates/manifest/AndroidManifest.xml.fixed
/bin/bash -c "(echo android.test.base android.test.mock | tr ' ' '\\n' > out/target/common/obj/APPS/Settings_intermediates/exported-sdk-libs.optional ) && (build/soong/scripts/manifest_fixer.py     --minSdkVersion 29           --targetSdkVersion 29           --raise-min-sdk-version     --uses-non-sdk-api --extract-native-libs=false          \$(cat out/target/common/obj/APPS/Settings_intermediates/exported-sdk-libs | grep -v -f out/target/common/obj/APPS/Settings_intermediates/exported-sdk-libs.optional | sort -u | sed -e 's/^/\\ --uses-library\\ /' | tr '\\n' ' ') \$(cat out/target/common/obj/APPS/Settings_intermediates/exported-sdk-libs | grep -f out/target/common/obj/APPS/Settings_intermediates/exported-sdk-libs.optional | sort -u | sed -e 's/^/\\ --optional-uses-library\\ /' | tr '\\n' ' ')      packages/apps/Settings/AndroidManifest.xml out/target/common/obj/APPS/Settings_intermediates/manifest/AndroidManifest.xml.fixed ) && (rm out/target/common/obj/APPS/Settings_intermediates/exported-sdk-libs.optional )"
error: mismatched tag: line 3346, column 6
12:05:31 ninja failed with: exit status 1

added banner and logo

added logo

added banner and logo

Update Android.mk

added branding

added animation and logo

added lower banner

added branding